
[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "cm_queue"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.0.0", features = ["async"] }
napi-derive = "3.0.0"
tokio = { version = "1.47.0", features = ["full"] }
[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
