/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface BranchStatus {
  root: string
  branch: string
  ahead: number
  behind: number
  staged: number
  conflicted: number
  changed: number
  untracked: number
}

export declare function gitStatus(dirs: Array<string>, limit?: number | undefined | null): Promise<Array<Error | BranchStatus>>

export declare function gitStatusWithFetch(dirs: Array<string>, limit?: number | undefined | null): Promise<Array<Error | BranchStatus>>
