/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function gitStatus(dirs: Array<string>, limit?: number | undefined | null): Promise<Array<Error | GitStatus>>

export interface GitStatus {
  root: string
  notAdded: Array<string>
  conflicted: Array<string>
  created: Array<string>
  deleted: Array<string>
  ignored: Array<string>
  modified: Array<string>
  renamed: Array<string>
  files: Array<string>
  staged: Array<string>
  ahead: number
  behind: number
  current?: string
  tracking?: string
  detached: boolean
  isClean: boolean
}

export declare function gitStatusWithFetch(dirs: Array<string>, limit?: number | undefined | null): Promise<Array<Error | GitStatus>>
